version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    restart: unless-stopped
